//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLCMinesweeperApp.GameServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameServices.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Bar", ReplyAction="http://tempuri.org/IService1/BarResponse")]
        string Bar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Bar", ReplyAction="http://tempuri.org/IService1/BarResponse")]
        System.Threading.Tasks.Task<string> BarAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Foo", ReplyAction="http://tempuri.org/IService1/FooResponse")]
        string Foo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Foo", ReplyAction="http://tempuri.org/IService1/FooResponse")]
        System.Threading.Tasks.Task<string> FooAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveGame", ReplyAction="http://tempuri.org/IService1/SaveGameResponse")]
        bool SaveGame(string board);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveGame", ReplyAction="http://tempuri.org/IService1/SaveGameResponse")]
        System.Threading.Tasks.Task<bool> SaveGameAsync(string board);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CLCMinesweeperApp.GameServices.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CLCMinesweeperApp.GameServices.IService1>, CLCMinesweeperApp.GameServices.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Bar() {
            return base.Channel.Bar();
        }
        
        public System.Threading.Tasks.Task<string> BarAsync() {
            return base.Channel.BarAsync();
        }
        
        public string Foo() {
            return base.Channel.Foo();
        }
        
        public System.Threading.Tasks.Task<string> FooAsync() {
            return base.Channel.FooAsync();
        }
        
        public bool SaveGame(string board) {
            return base.Channel.SaveGame(board);
        }
        
        public System.Threading.Tasks.Task<bool> SaveGameAsync(string board) {
            return base.Channel.SaveGameAsync(board);
        }
    }
}
